DELETE http://localhost:3003/api/blogs/6304d1de1aa1a944cf03d096
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2MzAzOGI3YzhiNmJmOTdkN2FmMmMyNjEiLCJpYXQiOjE2NjEyNTcxNzAsImV4cCI6MTY2MTI2MDc3MH0.LPL_rg8G129ltKZIcjILGiuGkVYJ-SYeP6vO2eutca4